--DML(M_CHARACTER)
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME") VALUES (1, 'だるま');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME") VALUES (2, 'ほおずき');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME") VALUES (3, 'おばけ');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME") VALUES (4, 'えび');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME") VALUES (5, 'はながみ');

COMMIT;