--DML(M_CHARACTER)
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME", "IMG_PATH") VALUES (1, 'だるま','/img/1.png');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME", "IMG_PATH") VALUES (2, 'ほおずき','/img/2.png');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME", "IMG_PATH") VALUES (3, 'おばけ','/img/3.png');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME", "IMG_PATH") VALUES (4, 'えび','/img/4.png');
INSERT INTO "M_CHARACTER" ("CHARACTER_ID", "CHARACTER_NAME", "IMG_PATH") VALUES (5, 'はながみ','/img/5.png');

COMMIT;
